Friendships v2
MrSayyod/ror-social-scaffold pull request #4
Opened 2020-08-21 14:57 UTC by MrSayyod

-    User is able to send a friendship invitation.
-    User can see a button “Invite to friendship” next to the name of user who is not his friend yet.
-    User is able to see pending friendship invitations sent to him.
-    User is able to accept or reject friendships invitation.
-    User can see posts created by himself and his friends in timeline.

2020-08-21 22:35 UTC, mosesogwo requested changes
**Hello!:wave: Nice job:+1:. Here are the required changes for this milestone to be approved:**

:point_right: With the reverse-pair of confirmed friendships setup, you can retrieve friends with associations like these
```ruby
# User model

has_many :confirmed_friendships, -> { where confirmed: true }, class_name: "Friendship"
has_many :friends, through: :confirmed_friendships
```
This is more efficient than filtering and selecting the records with enumerable methods.

:point_right: Here is a simpler method to retrieve timeline posts from User model.
```ruby
# User model

def friends_and_own_posts
  Post.where(user: (self.friends + self))
  # This will produce SQL query with IN. Something like: select * from posts where user_id IN (1,45,874,43);
end
```

:point_right: Friendship spec should cover a user successfully accepting or rejecting a friend request. So a click action should be made on those options and the proper expectations checked.

:point_right: Ensure that linter checks are running and passing.

:point_right: Extract view logic in application layout and posts index into helper methods.

_**Optional Changes**_
:point_right: It'd be nice to have an indicator in front of users to whom a friend request has been sent on the all users page. Also add the accept and delete options on all users page and on the user show page.

:point_right: You are encouraged to read about the n+1 problem [here](https://medium.com/@bretdoucette/n-1-queries-and-how-to-avoid-them-a12f02345be5) and avoid them in your project.

:point_right: To keep your routes RESTFUL, friendships controller accept, reject and cancel actions could be put into update and destroy actions.

2020-08-21 22:35 UTC, mosesogwo commented on app/models/user.rb
> +    friend_request = inverse_friendships.find { |friendship| friendship.user == user if friendship.status == -1 }
You could find the friend_request from _incoming\_friendships_ as you have done in **confirm_friendship(user)** above. Then, inverse_friendships association may no longer be needed, since we have reverse-pair records for each confirmed friendship.

2020-08-22 03:06 UTC, kobiyoyo requested changes
## Hi @MrSayyod     ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
#### Great Job so far, everything works fine, but there are a few more things required. 
### General
- [ ] Check comments below
### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

2020-08-22 03:06 UTC, kobiyoyo commented on app/models/user.rb
>    end
You can now remove this since you have used SQL query (`has_many :friends`) for data processing.

Note: kindly remove all methods that have been replaced with SQL query

2020-08-22 05:06 UTC, maelfosso requested changes
# Changes required :red_circle: 

Hello,

Thank you fo r applying the suggested changes.
However, there are some issues and missed requirements

1. Is indicated as a requirement, you can read it [here](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/user_can_see_invite_buttton.png), that there must be a button to invite user to friendship on users list page and on single user page. In your web app , those buttons are only available in the Single user page.. Please, add them also in the user liist

2. I notice something from your database that you have to fix
I created two users: Alice Bar and Bob Bar. You can notice that from this output from `rails console`
```rb
2.7.0 :001 > User.all
  User Load (0.6ms)  SELECT  "users".* FROM "users" LIMIT $1  [["LIMIT", 11]]
 => #<ActiveRecord::Relation [#<User id: 1, email: "alice@bar.com", created_at: "2020-08-22 04:39:56", updated_at: "2020-08-22 04:39:56", name: "Alice Bar", gravatar_url: nil>, #<User id: 2, email: "bob@bar.com", created_at: "2020-08-22 04:40:21", updated_at: "2020-08-22 04:40:21", name: "Bob Bar", gravatar_url: nil>]>
```
There are exactly two users.

Then I sent a friendship request from Bob Bar to Alice Bar. 
The content of the `Friendship` table is depicted below
```rb
2.7.0 :002 > Friendship.all
  Friendship Load (0.6ms)  SELECT  "friendships".* FROM "friendships" LIMIT $1  [["LIMIT", 11]]
 => #<ActiveRecord::Relation [#<Friendship id: 1, user_id: 1, friend_id: 1, created_at: "2020-08-22 04:39:56", updated_at: "2020-08-22 04:39:56", status: 1>, #<Friendship id: 2, user_id: 1, friend_id: 1, created_at: "2020-08-22 04:39:59", updated_at: "2020-08-22 04:39:59", status: 1>, #<Friendship id: 3, user_id: 2, friend_id: 2, created_at: "2020-08-22 04:40:21", updated_at: "2020-08-22 04:40:21", status: 1>, #<Friendship id: 4, user_id: 2, friend_id: 2, created_at: "2020-08-22 04:40:23", updated_at: "2020-08-22 04:40:23", status: 1>, #<Friendship id: 5, user_id: 2, friend_id: 1, created_at: "2020-08-22 04:40:25", updated_at: "2020-08-22 04:40:25", status: -1>]> 
2.7.0 :003 > Friendship.count
   (17.6ms)  SELECT COUNT(*) FROM "friendships"
 => 5 
2.7.0 :004 >
```
You will notice that there are **5 rows** for only one friendship request sent.
**Questions**: WHY? 
**We expect only two rows in that table at this step.** There are multiple friendships between User1 and User1, User2 and USer2. Which are not needed!!!
Kindly fix that please.

After, Alice Bar have accepted the Friendship request sent by Bob Bar, the `Friendship` table content has changed as follow
```rb
2.7.0 :002 > Friendship.all
  Friendship Load (0.6ms)  SELECT  "friendships".* FROM "friendships" LIMIT $1  [["LIMIT", 11]]
 => #<ActiveRecord::Relation [#<Friendship id: 1, user_id: 1, friend_id: 1, created_at: "2020-08-22 04:39:56", updated_at: "2020-08-22 04:39:56", status: 1>, #<Friendship id: 2, user_id: 1, friend_id: 1, created_at: "2020-08-22 04:39:59", updated_at: "2020-08-22 04:39:59", status: 1>, #<Friendship id: 3, user_id: 2, friend_id: 2, created_at: "2020-08-22 04:40:21", updated_at: "2020-08-22 04:40:21", status: 1>, #<Friendship id: 4, user_id: 2, friend_id: 2, created_at: "2020-08-22 04:40:23", updated_at: "2020-08-22 04:40:23", status: 1>, #<Friendship id: 6, user_id: 1, friend_id: 1, created_at: "2020-08-22 04:42:46", updated_at: "2020-08-22 04:42:46", status: 1>, #<Friendship id: 5, user_id: 2, friend_id: 1, created_at: "2020-08-22 04:40:25", updated_at: "2020-08-22 04:42:51", status: 1>, #<Friendship id: 7, user_id: 1, friend_id: 2, created_at: "2020-08-22 04:42:51", updated_at: "2020-08-22 04:42:51", status: 1>, #<Friendship id: 8, user_id: 1, friend_id: 1, created_at: "2020-08-22 04:42:58", updated_at: "2020-08-22 04:42:58", status: 1>]> 
2.7.0 :003 > 
2.7.0 :004 > Friendship.count
   (0.8ms)  SELECT COUNT(*) FROM "friendships"
 => 8 
2.7.0 :005 >
```
Now, the number of rows has increased by **3**. WHY? **There are duplicated rows!!!**.
At that step, there should have only **2 rows** into that table.

Kindly fix it!

3- REad the comments left below, please.

4- Please, Update your integration tests. In the integration tests, there is not requests from your code. 
Something like this `Friendship.create(user_id: user2.id, friend_id: user1.id, status: -1)` must not be in your code. 
You must navigate, click, visit page. And expect something from your table or the page.
Fix that please. Take a look at this https://www.codewithjason.com/rails-integration-tests-rspec-capybara/ please.

Once done, please submit a new code review request.
Thanks

Mael FOSSO

2020-08-22 05:06 UTC, maelfosso commented on app/models/user.rb
>    end
The first parameter is not needed. Remove it and just call it like it
```rb
current_user.send_friend_request(friend)
```

2020-08-22 05:06 UTC, maelfosso commented on app/controllers/users_controller.rb
> +    @friend = User.find(params[:friend_id])
Why do you need that request? 
The only thing that you will use there is the friend id which is the one send in the request.

2020-08-24 16:34 UTC, MrSayyod commented on app/models/user.rb
>    end
In controller I need to identify current user and friend. That's why I've used 2 parameters

2020-08-24 16:38 UTC, MrSayyod commented on app/controllers/users_controller.rb
> +    @friend = User.find(params[:friend_id])
```
@friend = User.find(params[:friend_id])
@invitation = current_user.confirm_friendship(@friend)
```
First version of code was like this:
```
 @invitation = current_user.confirm_friendship(User.find(params[:friend_id]))
```
Then I refactored the code to be easy to understand.

2020-08-24 19:48 UTC, kobiyoyo requested changes
## Hi @MrSayyod     ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
#### Great Job so far, everything works fine, but there are a few more things required. 
### General
- [x] Let's fix this, anytime i send a friend request i see myself on the friend list .
- [ ] Lets fix changes requested by previous TSE concerning database, because i had the same issue were just one friendship created 5 rows.
  
### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

2020-12-17 08:09 UTC, MrSayyod commented
It is showing 2 queries on my machine

2020-12-17 16:47 UTC, tirthajyoti-ghosh approved these changes
# Approved ✅

## You have done an incredible job making this project 👏🧨💪! Just perfect 💯! 

### You have met all the requirements of the project. Go ahead and merge it! Onto the next project 🚀 !

Happy coding 👨‍💻 

<hr>

**Tirthajyoti Ghosh**

[GitHub](https://github.com/tirthajyoti-ghosh) | [LinkedIn](https://www.linkedin.com/in/tirthajyoti-ghosh/) | [Twitter](https://twitter.com/terrific_ghosh)

2020-12-18 14:06 UTC, merged